name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run unit tests
        run: python -m unittest discover -s tests
      - name: Build Docker image
        run: docker build -t tradesocio-devops-challenge .
      - name: Run container tests
        run: |
          curl -sSL https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 > container-structure-test
          chmod +x container-structure-test
          ./container-structure-test test --image tradesocio-devops-challenge --config tests/container-test.yaml
      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag tradesocio-devops-challenge abhishek7868/tradesocio-devops-challenge:latest
          docker push abhishek7868/tradesocio-devops-challenge:latest